# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

---
image: registry.heinlein.group/opentalk-tools/rust:1.97-trixie

.template_vars:
  FLAVORS: [trixie]
  DEFAULT_FLAVOR: trixie

.default_job_condition: &default_job_condition
  needs: []
  rules:
    # Run in merge requests (if there is one job with this instruction, all jobs without
    # it are ignored for the MR pipeline)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run on scheduled pipeline runs
    - if: $CI_PIPELINE_SOURCE == 'schedule'

stages:
  - lint
  - test
  - release
  - package
  - build
  - push

include:
  - project: opentalk/ci/templates/collect-commit-evidence
    ref: v2
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/rust-lint
    ref: v1
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/common-lint
    ref: v1
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/changelog
    ref: v2
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/rust-container-build
    inputs:
      harbor_namespace_suffix: ci-doc-updater
      harbor_push_project: opentalk/opentalk-devops/push-and-sign-images-for-the-opentalk-tools-namespace
    ref: v2
    file: .gitlab-ci-template.yml

test:cargo_test:
  stage: test
  needs: []
  rules:
    # Run in merge requests (if there is one job with this instruction, all jobs without
    # it are ignored for the MR pipeline)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run on scheduled pipeline runs
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    # Also run on protected branches and tags to ensure we detect any issues with the merge
    - if: $CI_COMMIT_REF_PROTECTED == 'true'
  artifacts:
    paths:
      - target/coverage/html
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/coverage/cobertura.xml
  coverage: '/Coverage: \d+(?:\.\d+)?/'
  variables:
    FF_NETWORK_PER_BUILD: 'true'
    # Used for coverage
    COVERAGE_XML_PATH: 'concat("Coverage: ", 100 * string(//coverage/@line-rate), "%")'

  before_script:
    - rustup component add rustfmt llvm-tools-preview
    # libxml2-utils contains the xmllint command used below
    - apt-get update && apt-get install -y libxml2-utils
  script:
    - RUSTFLAGS="-C instrument-coverage -C link-arg=-fuse-ld=lld"
      LLVM_PROFILE_FILE="$(pwd)/target/coverage/raw/coverage-%p-%m.profraw"
      cargo test --workspace --locked

    # Extract code coverage data
    - grcov target/coverage/raw
      --binary-path ./target/debug/
      --source-dir .
      --output-types cobertura,html
      --branch
      --ignore-not-existing
      --ignore "*cargo*"
      --output-path target/coverage

    # Print out the coverage percentage for GitLab
    - xmllint --xpath "$COVERAGE_XML_PATH" target/coverage/cobertura.xml

test:cargo_publish:
  stage: test
  needs: []
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9-\.]+)?$/
    - if: $CI_COMMIT_REF_NAME =~ /main/
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - cargo publish --package opentalk-ci-doc-updater --dry-run --no-verify

release:cargo_publish:
  stage: release
  needs: [test:cargo_publish]
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9-\.]+)?$/
  script:
    - cargo publish --package opentalk-ci-doc-updater

build:
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG != null
  artifacts:
    paths:
      - target/release/opentalk-ci-doc-updater
    expire_in: 1 week
  script:
    - cargo auditable build --release --locked --workspace

package:container-build-mr:
  needs:
    - build

package:container-build:
  needs:
    - build
