# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

SPDX-PackageDownloadLocation = "https://git.opentalk.dev/opentalk/tools/opentalk-ci-doc-updater/"
SPDX-PackageName = "OpenTalk CI Documentation Updater"
SPDX-PackageSupplier = "OpenTalk GmbH <mail@opentalk.eu>"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "OpenTalk GmbH <mail@opentalk.eu>"
SPDX-License-Identifier = "EUPL-1.2"
path = [
  "README.md",
  ".commitlintrc.json",
  "CHANGELOG.md",
  "Cargo.lock",
  "renovate.json",
]
precedence = "aggregate"
