# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
# SPDX-License-Identifier: EUPL-1.2

FROM debian:bookworm-slim

COPY target/release/opentalk-ci-doc-updater /usr/local/bin/opentalk-ci-doc-updater
